(define (problem TOWERS-4)
  (:domain TOWERS)
  (:objects A B C D - disk X Y Z - tower)
  (:INIT
    (disk_on_top_of_tower A X)
    (under_disk B A)
    (under_disk C B)
    (under_disk D C)
    (last_disk D)
    (bigger_disk D C)
    (bigger_disk D B)
    (bigger_disk D A)
    (bigger_disk C B)
    (bigger_disk C A)
    (bigger_disk B A)
    (empty_tower Y)
    (empty_tower Z)
    (hand_empty)
  )
  (:goal (and
           (disk_on_top_of_tower A Z)
           (under_disk B A)
           (under_disk C B)
           (under_disk D C)
         )
  )
)
