(define (problem TOWERS-3)
  (:domain TOWERS)
  (:objects A B C - disk X Y Z - tower)
  (:INIT
    (disk_on_top_of_tower A X)
    (under_disk B A)
    (under_disk C B)
    (last_disk C)
    (bigger_disk C B)
    (bigger_disk C A)
    (bigger_disk B A)
    (empty_tower Y)
    (empty_tower Z)
    (hand_empty)
  )
  (:goal (and
           (disk_on_top_of_tower A Z)
           (under_disk B A)
           (under_disk C B)
         )
  )
)
