(define (problem TOWERS-7)
  (:domain TOWERS)
  (:objects A B C D E F G - disk X Y Z - tower)
  (:INIT
    (disk_on_top_of_tower A X)
    (under_disk B A)
    (under_disk C B)
    (under_disk D C)
    (under_disk E D)
    (under_disk F E)
    (under_disk G F)
    (last_disk G)
    (bigger_disk G F)
    (bigger_disk G E)
    (bigger_disk G D)
    (bigger_disk G C)
    (bigger_disk G B)
    (bigger_disk G A)
    (bigger_disk F E)
    (bigger_disk F D)
    (bigger_disk F C)
    (bigger_disk F B)
    (bigger_disk F A)
    (bigger_disk E D)
    (bigger_disk E C)
    (bigger_disk E B)
    (bigger_disk E A)
    (bigger_disk D C)
    (bigger_disk D B)
    (bigger_disk D A)
    (bigger_disk C B)
    (bigger_disk C A)
    (bigger_disk B A)
    (empty_tower Y)
    (empty_tower Z)
    (hand_empty)
  )
  (:goal (and
           (disk_on_top_of_tower A Z)
           (under_disk B A)
           (under_disk C B)
           (under_disk D C)
           (under_disk E D)
           (under_disk F E)
           (under_disk G F)
         )
  )
)
